---
title: "Codebook"
author: "Vidya"
date: "13/03/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
> library(data.table)
data.table 1.14.2 using 4 threads (see ?getDTthreads).  Latest news: r-datatable.com
> library(dplyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:data.table’:

    between, first, last

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union
## Read all training and test files
> featureNames <- read.table("UCI HAR Dataset/features.txt")
> activityLabels <- read.table("UCI HAR Dataset/activity_labels.txt", header = FALSE)
> subjectTrain <- read.table("UCI HAR Dataset/train/subject_train.txt", header = FALSE)
> activityTrain <- read.table("UCI HAR Dataset/train/y_train.txt", header = FALSE)
> featuresTrain <- read.table("UCI HAR Dataset/train/X_train.txt", header = FALSE)
> subjectTest <- read.table("UCI HAR Dataset/test/subject_test.txt", header = FALSE)
> activityTest <- read.table("UCI HAR Dataset/test/y_test.txt", header = FALSE)
> featuresTest <- read.table("UCI HAR Dataset/test/X_test.txt", header = FALSE)
## Merge training and test datasets using rbind() function and store the data in features, activity and subject in one completeDAta
> subject <- rbind(subjectTrain, subjectTest)
> activity <- rbind(activityTrain, activityTest)
> features <- rbind(featuresTrain, featuresTest)
> subject <- rbind(subjectTrain, subjectTest)
> activity <- rbind(activityTrain, activityTest)
> features <- rbind(featuresTrain, featuresTest)
> colnames(features) <- t(featureNames[2])
> colnames(activity) <- "Activity"
> colnames(subject) <- "Subject"
> completeData <- cbind(features,activity,subject)
## Name the columns and extract measurements on mean and standard deviation
> columnsWithMeanSTD <- grep(".*Mean.*|.*Std.*", names(completeData), ignore.case=TRUE)
> requiredColumns <- c(columnsWithMeanSTD, 562, 563)
> dim(completeData)
[1] 10299   563
> extractedData <- completeData[,requiredColumns]
> dim(extractedData)
[1] 10299    88
> extractedData$Activity <- as.character(extractedData$Activity)
> for (i in 1:6){
+     extractedData$Activity[extractedData$Activity == i] <- as.character(activityLabels[i,2])
+ }
> extractedData$Activity <- as.factor(extractedData$Activity)
> names(extractedData)
 [1] "tBodyAcc-mean()-X"                   
 [2] "tBodyAcc-mean()-Y"                   
 [3] "tBodyAcc-mean()-Z"                   
 [4] "tBodyAcc-std()-X"                    
 [5] "tBodyAcc-std()-Y"                    
 [6] "tBodyAcc-std()-Z"                    
 [7] "tGravityAcc-mean()-X"                
 [8] "tGravityAcc-mean()-Y"                
 [9] "tGravityAcc-mean()-Z"                
[10] "tGravityAcc-std()-X"                 
[11] "tGravityAcc-std()-Y"                 
[12] "tGravityAcc-std()-Z"                 
[13] "tBodyAccJerk-mean()-X"               
[14] "tBodyAccJerk-mean()-Y"               
[15] "tBodyAccJerk-mean()-Z"               
[16] "tBodyAccJerk-std()-X"                
[17] "tBodyAccJerk-std()-Y"                
[18] "tBodyAccJerk-std()-Z"                
[19] "tBodyGyro-mean()-X"                  
[20] "tBodyGyro-mean()-Y"                  
[21] "tBodyGyro-mean()-Z"                  
[22] "tBodyGyro-std()-X"                   
[23] "tBodyGyro-std()-Y"                   
[24] "tBodyGyro-std()-Z"                   
[25] "tBodyGyroJerk-mean()-X"              
[26] "tBodyGyroJerk-mean()-Y"              
[27] "tBodyGyroJerk-mean()-Z"              
[28] "tBodyGyroJerk-std()-X"               
[29] "tBodyGyroJerk-std()-Y"               
[30] "tBodyGyroJerk-std()-Z"               
[31] "tBodyAccMag-mean()"                  
[32] "tBodyAccMag-std()"                   
[33] "tGravityAccMag-mean()"               
[34] "tGravityAccMag-std()"                
[35] "tBodyAccJerkMag-mean()"              
[36] "tBodyAccJerkMag-std()"               
[37] "tBodyGyroMag-mean()"                 
[38] "tBodyGyroMag-std()"                  
[39] "tBodyGyroJerkMag-mean()"             
[40] "tBodyGyroJerkMag-std()"              
[41] "fBodyAcc-mean()-X"                   
[42] "fBodyAcc-mean()-Y"                   
[43] "fBodyAcc-mean()-Z"                   
[44] "fBodyAcc-std()-X"                    
[45] "fBodyAcc-std()-Y"                    
[46] "fBodyAcc-std()-Z"                    
[47] "fBodyAcc-meanFreq()-X"               
[48] "fBodyAcc-meanFreq()-Y"               
[49] "fBodyAcc-meanFreq()-Z"               
[50] "fBodyAccJerk-mean()-X"               
[51] "fBodyAccJerk-mean()-Y"               
[52] "fBodyAccJerk-mean()-Z"               
[53] "fBodyAccJerk-std()-X"                
[54] "fBodyAccJerk-std()-Y"                
[55] "fBodyAccJerk-std()-Z"                
[56] "fBodyAccJerk-meanFreq()-X"           
[57] "fBodyAccJerk-meanFreq()-Y"           
[58] "fBodyAccJerk-meanFreq()-Z"           
[59] "fBodyGyro-mean()-X"                  
[60] "fBodyGyro-mean()-Y"                  
[61] "fBodyGyro-mean()-Z"                  
[62] "fBodyGyro-std()-X"                   
[63] "fBodyGyro-std()-Y"                   
[64] "fBodyGyro-std()-Z"                   
[65] "fBodyGyro-meanFreq()-X"              
[66] "fBodyGyro-meanFreq()-Y"              
[67] "fBodyGyro-meanFreq()-Z"              
[68] "fBodyAccMag-mean()"                  
[69] "fBodyAccMag-std()"                   
[70] "fBodyAccMag-meanFreq()"              
[71] "fBodyBodyAccJerkMag-mean()"          
[72] "fBodyBodyAccJerkMag-std()"           
[73] "fBodyBodyAccJerkMag-meanFreq()"      
[74] "fBodyBodyGyroMag-mean()"             
[75] "fBodyBodyGyroMag-std()"              
[76] "fBodyBodyGyroMag-meanFreq()"         
[77] "fBodyBodyGyroJerkMag-mean()"         
[78] "fBodyBodyGyroJerkMag-std()"          
[79] "fBodyBodyGyroJerkMag-meanFreq()"     
[80] "angle(tBodyAccMean,gravity)"         
[81] "angle(tBodyAccJerkMean),gravityMean)"
[82] "angle(tBodyGyroMean,gravityMean)"    
[83] "angle(tBodyGyroJerkMean,gravityMean)"
[84] "angle(X,gravityMean)"                
[85] "angle(Y,gravityMean)"                
[86] "angle(Z,gravityMean)"                
[87] "Activity"                            
[88] "Subject"       
## Descriptive variable names assigned to the dataset
> names(extractedData)<-gsub("Acc", "Accelerometer", names(extractedData))
> names(extractedData)<-gsub("Gyro", "Gyroscope", names(extractedData))
> names(extractedData)<-gsub("BodyBody", "Body", names(extractedData))
> names(extractedData)<-gsub("Mag", "Magnitude", names(extractedData))
> names(extractedData)<-gsub("^t", "Time", names(extractedData))
> names(extractedData)<-gsub("^f", "Frequency", names(extractedData))
> names(extractedData)<-gsub("tBody", "TimeBody", names(extractedData))
> names(extractedData)<-gsub("-mean()", "Mean", names(extractedData), ignore.case = TRUE)
> names(extractedData)<-gsub("-std()", "STD", names(extractedData), ignore.case = TRUE)
> names(extractedData)<-gsub("-freq()", "Frequency", names(extractedData), ignore.case = TRUE)
> names(extractedData)<-gsub("angle", "Angle", names(extractedData))
> names(extractedData)<-gsub("gravity", "Gravity", names(extractedData))
> names(extractedData)
 [1] "TimeBodyAccelerometerMean()-X"                    
 [2] "TimeBodyAccelerometerMean()-Y"                    
 [3] "TimeBodyAccelerometerMean()-Z"                    
 [4] "TimeBodyAccelerometerSTD()-X"                     
 [5] "TimeBodyAccelerometerSTD()-Y"                     
 [6] "TimeBodyAccelerometerSTD()-Z"                     
 [7] "TimeGravityAccelerometerMean()-X"                 
 [8] "TimeGravityAccelerometerMean()-Y"                 
 [9] "TimeGravityAccelerometerMean()-Z"                 
[10] "TimeGravityAccelerometerSTD()-X"                  
[11] "TimeGravityAccelerometerSTD()-Y"                  
[12] "TimeGravityAccelerometerSTD()-Z"                  
[13] "TimeBodyAccelerometerJerkMean()-X"                
[14] "TimeBodyAccelerometerJerkMean()-Y"                
[15] "TimeBodyAccelerometerJerkMean()-Z"                
[16] "TimeBodyAccelerometerJerkSTD()-X"                 
[17] "TimeBodyAccelerometerJerkSTD()-Y"                 
[18] "TimeBodyAccelerometerJerkSTD()-Z"                 
[19] "TimeBodyGyroscopeMean()-X"                        
[20] "TimeBodyGyroscopeMean()-Y"                        
[21] "TimeBodyGyroscopeMean()-Z"                        
[22] "TimeBodyGyroscopeSTD()-X"                         
[23] "TimeBodyGyroscopeSTD()-Y"                         
[24] "TimeBodyGyroscopeSTD()-Z"                         
[25] "TimeBodyGyroscopeJerkMean()-X"                    
[26] "TimeBodyGyroscopeJerkMean()-Y"                    
[27] "TimeBodyGyroscopeJerkMean()-Z"                    
[28] "TimeBodyGyroscopeJerkSTD()-X"                     
[29] "TimeBodyGyroscopeJerkSTD()-Y"                     
[30] "TimeBodyGyroscopeJerkSTD()-Z"                     
[31] "TimeBodyAccelerometerMagnitudeMean()"             
[32] "TimeBodyAccelerometerMagnitudeSTD()"              
[33] "TimeGravityAccelerometerMagnitudeMean()"          
[34] "TimeGravityAccelerometerMagnitudeSTD()"           
[35] "TimeBodyAccelerometerJerkMagnitudeMean()"         
[36] "TimeBodyAccelerometerJerkMagnitudeSTD()"          
[37] "TimeBodyGyroscopeMagnitudeMean()"                 
[38] "TimeBodyGyroscopeMagnitudeSTD()"                  
[39] "TimeBodyGyroscopeJerkMagnitudeMean()"             
[40] "TimeBodyGyroscopeJerkMagnitudeSTD()"              
[41] "FrequencyBodyAccelerometerMean()-X"               
[42] "FrequencyBodyAccelerometerMean()-Y"               
[43] "FrequencyBodyAccelerometerMean()-Z"               
[44] "FrequencyBodyAccelerometerSTD()-X"                
[45] "FrequencyBodyAccelerometerSTD()-Y"                
[46] "FrequencyBodyAccelerometerSTD()-Z"                
[47] "FrequencyBodyAccelerometerMeanFreq()-X"           
[48] "FrequencyBodyAccelerometerMeanFreq()-Y"           
[49] "FrequencyBodyAccelerometerMeanFreq()-Z"           
[50] "FrequencyBodyAccelerometerJerkMean()-X"           
[51] "FrequencyBodyAccelerometerJerkMean()-Y"           
[52] "FrequencyBodyAccelerometerJerkMean()-Z"           
[53] "FrequencyBodyAccelerometerJerkSTD()-X"            
[54] "FrequencyBodyAccelerometerJerkSTD()-Y"            
[55] "FrequencyBodyAccelerometerJerkSTD()-Z"            
[56] "FrequencyBodyAccelerometerJerkMeanFreq()-X"       
[57] "FrequencyBodyAccelerometerJerkMeanFreq()-Y"       
[58] "FrequencyBodyAccelerometerJerkMeanFreq()-Z"       
[59] "FrequencyBodyGyroscopeMean()-X"                   
[60] "FrequencyBodyGyroscopeMean()-Y"                   
[61] "FrequencyBodyGyroscopeMean()-Z"                   
[62] "FrequencyBodyGyroscopeSTD()-X"                    
[63] "FrequencyBodyGyroscopeSTD()-Y"                    
[64] "FrequencyBodyGyroscopeSTD()-Z"                    
[65] "FrequencyBodyGyroscopeMeanFreq()-X"               
[66] "FrequencyBodyGyroscopeMeanFreq()-Y"               
[67] "FrequencyBodyGyroscopeMeanFreq()-Z"               
[68] "FrequencyBodyAccelerometerMagnitudeMean()"        
[69] "FrequencyBodyAccelerometerMagnitudeSTD()"         
[70] "FrequencyBodyAccelerometerMagnitudeMeanFreq()"    
[71] "FrequencyBodyAccelerometerJerkMagnitudeMean()"    
[72] "FrequencyBodyAccelerometerJerkMagnitudeSTD()"     
[73] "FrequencyBodyAccelerometerJerkMagnitudeMeanFreq()"
[74] "FrequencyBodyGyroscopeMagnitudeMean()"            
[75] "FrequencyBodyGyroscopeMagnitudeSTD()"             
[76] "FrequencyBodyGyroscopeMagnitudeMeanFreq()"        
[77] "FrequencyBodyGyroscopeJerkMagnitudeMean()"        
[78] "FrequencyBodyGyroscopeJerkMagnitudeSTD()"         
[79] "FrequencyBodyGyroscopeJerkMagnitudeMeanFreq()"    
[80] "Angle(TimeBodyAccelerometerMean,Gravity)"         
[81] "Angle(TimeBodyAccelerometerJerkMean),GravityMean)"
[82] "Angle(TimeBodyGyroscopeMean,GravityMean)"         
[83] "Angle(TimeBodyGyroscopeJerkMean,GravityMean)"     
[84] "Angle(X,GravityMean)"                             
[85] "Angle(Y,GravityMean)"                             
[86] "Angle(Z,GravityMean)"                             
[87] "Activity"                                         
[88] "Subject"   
## Tidy dataset containing the average of each variable created and stored in Tidy.txt
> extractedData$Subject <- as.factor(extractedData$Subject)
> extractedData <- data.table(extractedData)
> tidyData <- aggregate(. ~Subject + Activity, extractedData, mean)
> tidyData <- tidyData[order(tidyData$Subject,tidyData$Activity),]
> write.table(tidyData, file = "Tidy.txt", row.names = FALSE)
> tidyaData
Error: object 'tidyaData' not found
> str(tidyData)
'data.frame':	180 obs. of  88 variables:
 $ Subject                                          : Factor w/ 30 levels "1","2","3","4",..: 1 1 1 1 1 1 2 2 2 2 ...
 $ Activity                                         : Factor w/ 6 levels "LAYING","SITTING",..: 1 2 3 4 5 6 1 2 3 4 ...
 $ TimeBodyAccelerometerMean()-X                    : num  0.222 0.261 0.279 0.277 0.289 ...
 $ TimeBodyAccelerometerMean()-Y                    : num  -0.04051 -0.00131 -0.01614 -0.01738 -0.00992 ...
 $ TimeBodyAccelerometerMean()-Z                    : num  -0.113 -0.105 -0.111 -0.111 -0.108 ...
 $ TimeBodyAccelerometerSTD()-X                     : num  -0.928 -0.977 -0.996 -0.284 0.03 ...
 $ TimeBodyAccelerometerSTD()-Y                     : num  -0.8368 -0.9226 -0.9732 0.1145 -0.0319 ...
 $ TimeBodyAccelerometerSTD()-Z                     : num  -0.826 -0.94 -0.98 -0.26 -0.23 ...
 $ TimeGravityAccelerometerMean()-X                 : num  -0.249 0.832 0.943 0.935 0.932 ...
 $ TimeGravityAccelerometerMean()-Y                 : num  0.706 0.204 -0.273 -0.282 -0.267 ...
 $ TimeGravityAccelerometerMean()-Z                 : num  0.4458 0.332 0.0135 -0.0681 -0.0621 ...
 $ TimeGravityAccelerometerSTD()-X                  : num  -0.897 -0.968 -0.994 -0.977 -0.951 ...
 $ TimeGravityAccelerometerSTD()-Y                  : num  -0.908 -0.936 -0.981 -0.971 -0.937 ...
 $ TimeGravityAccelerometerSTD()-Z                  : num  -0.852 -0.949 -0.976 -0.948 -0.896 ...
 $ TimeBodyAccelerometerJerkMean()-X                : num  0.0811 0.0775 0.0754 0.074 0.0542 ...
 $ TimeBodyAccelerometerJerkMean()-Y                : num  0.003838 -0.000619 0.007976 0.028272 0.02965 ...
 $ TimeBodyAccelerometerJerkMean()-Z                : num  0.01083 -0.00337 -0.00369 -0.00417 -0.01097 ...
 $ TimeBodyAccelerometerJerkSTD()-X                 : num  -0.9585 -0.9864 -0.9946 -0.1136 -0.0123 ...
 $ TimeBodyAccelerometerJerkSTD()-Y                 : num  -0.924 -0.981 -0.986 0.067 -0.102 ...
 $ TimeBodyAccelerometerJerkSTD()-Z                 : num  -0.955 -0.988 -0.992 -0.503 -0.346 ...
 $ TimeBodyGyroscopeMean()-X                        : num  -0.0166 -0.0454 -0.024 -0.0418 -0.0351 ...
 $ TimeBodyGyroscopeMean()-Y                        : num  -0.0645 -0.0919 -0.0594 -0.0695 -0.0909 ...
 $ TimeBodyGyroscopeMean()-Z                        : num  0.1487 0.0629 0.0748 0.0849 0.0901 ...
 $ TimeBodyGyroscopeSTD()-X                         : num  -0.874 -0.977 -0.987 -0.474 -0.458 ...
 $ TimeBodyGyroscopeSTD()-Y                         : num  -0.9511 -0.9665 -0.9877 -0.0546 -0.1263 ...
 $ TimeBodyGyroscopeSTD()-Z                         : num  -0.908 -0.941 -0.981 -0.344 -0.125 ...
 $ TimeBodyGyroscopeJerkMean()-X                    : num  -0.1073 -0.0937 -0.0996 -0.09 -0.074 ...
 $ TimeBodyGyroscopeJerkMean()-Y                    : num  -0.0415 -0.0402 -0.0441 -0.0398 -0.044 ...
 $ TimeBodyGyroscopeJerkMean()-Z                    : num  -0.0741 -0.0467 -0.049 -0.0461 -0.027 ...
 $ TimeBodyGyroscopeJerkSTD()-X                     : num  -0.919 -0.992 -0.993 -0.207 -0.487 ...
 $ TimeBodyGyroscopeJerkSTD()-Y                     : num  -0.968 -0.99 -0.995 -0.304 -0.239 ...
 $ TimeBodyGyroscopeJerkSTD()-Z                     : num  -0.958 -0.988 -0.992 -0.404 -0.269 ...
 $ TimeBodyAccelerometerMagnitudeMean()             : num  -0.8419 -0.9485 -0.9843 -0.137 0.0272 ...
 $ TimeBodyAccelerometerMagnitudeSTD()              : num  -0.7951 -0.9271 -0.9819 -0.2197 0.0199 ...
 $ TimeGravityAccelerometerMagnitudeMean()          : num  -0.8419 -0.9485 -0.9843 -0.137 0.0272 ...
 $ TimeGravityAccelerometerMagnitudeSTD()           : num  -0.7951 -0.9271 -0.9819 -0.2197 0.0199 ...
 $ TimeBodyAccelerometerJerkMagnitudeMean()         : num  -0.9544 -0.9874 -0.9924 -0.1414 -0.0894 ...
 $ TimeBodyAccelerometerJerkMagnitudeSTD()          : num  -0.9282 -0.9841 -0.9931 -0.0745 -0.0258 ...
 $ TimeBodyGyroscopeMagnitudeMean()                 : num  -0.8748 -0.9309 -0.9765 -0.161 -0.0757 ...
 $ TimeBodyGyroscopeMagnitudeSTD()                  : num  -0.819 -0.935 -0.979 -0.187 -0.226 ...
 $ TimeBodyGyroscopeJerkMagnitudeMean()             : num  -0.963 -0.992 -0.995 -0.299 -0.295 ...
 $ TimeBodyGyroscopeJerkMagnitudeSTD()              : num  -0.936 -0.988 -0.995 -0.325 -0.307 ...
 $ FrequencyBodyAccelerometerMean()-X               : num  -0.9391 -0.9796 -0.9952 -0.2028 0.0382 ...
 $ FrequencyBodyAccelerometerMean()-Y               : num  -0.86707 -0.94408 -0.97707 0.08971 0.00155 ...
 $ FrequencyBodyAccelerometerMean()-Z               : num  -0.883 -0.959 -0.985 -0.332 -0.226 ...
 $ FrequencyBodyAccelerometerSTD()-X                : num  -0.9244 -0.9764 -0.996 -0.3191 0.0243 ...
 $ FrequencyBodyAccelerometerSTD()-Y                : num  -0.834 -0.917 -0.972 0.056 -0.113 ...
 $ FrequencyBodyAccelerometerSTD()-Z                : num  -0.813 -0.934 -0.978 -0.28 -0.298 ...
 $ FrequencyBodyAccelerometerMeanFreq()-X           : num  -0.1588 -0.0495 0.0865 -0.2075 -0.3074 ...
 $ FrequencyBodyAccelerometerMeanFreq()-Y           : num  0.0975 0.0759 0.1175 0.1131 0.0632 ...
 $ FrequencyBodyAccelerometerMeanFreq()-Z           : num  0.0894 0.2388 0.2449 0.0497 0.2943 ...
 $ FrequencyBodyAccelerometerJerkMean()-X           : num  -0.9571 -0.9866 -0.9946 -0.1705 -0.0277 ...
 $ FrequencyBodyAccelerometerJerkMean()-Y           : num  -0.9225 -0.9816 -0.9854 -0.0352 -0.1287 ...
 $ FrequencyBodyAccelerometerJerkMean()-Z           : num  -0.948 -0.986 -0.991 -0.469 -0.288 ...
 $ FrequencyBodyAccelerometerJerkSTD()-X            : num  -0.9642 -0.9875 -0.9951 -0.1336 -0.0863 ...
 $ FrequencyBodyAccelerometerJerkSTD()-Y            : num  -0.932 -0.983 -0.987 0.107 -0.135 ...
 $ FrequencyBodyAccelerometerJerkSTD()-Z            : num  -0.961 -0.988 -0.992 -0.535 -0.402 ...
 $ FrequencyBodyAccelerometerJerkMeanFreq()-X       : num  0.132 0.257 0.314 -0.209 -0.253 ...
 $ FrequencyBodyAccelerometerJerkMeanFreq()-Y       : num  0.0245 0.0475 0.0392 -0.3862 -0.3376 ...
 $ FrequencyBodyAccelerometerJerkMeanFreq()-Z       : num  0.02439 0.09239 0.13858 -0.18553 0.00937 ...
 $ FrequencyBodyGyroscopeMean()-X                   : num  -0.85 -0.976 -0.986 -0.339 -0.352 ...
 $ FrequencyBodyGyroscopeMean()-Y                   : num  -0.9522 -0.9758 -0.989 -0.1031 -0.0557 ...
 $ FrequencyBodyGyroscopeMean()-Z                   : num  -0.9093 -0.9513 -0.9808 -0.2559 -0.0319 ...
 $ FrequencyBodyGyroscopeSTD()-X                    : num  -0.882 -0.978 -0.987 -0.517 -0.495 ...
 $ FrequencyBodyGyroscopeSTD()-Y                    : num  -0.9512 -0.9623 -0.9871 -0.0335 -0.1814 ...
 $ FrequencyBodyGyroscopeSTD()-Z                    : num  -0.917 -0.944 -0.982 -0.437 -0.238 ...
 $ FrequencyBodyGyroscopeMeanFreq()-X               : num  -0.00355 0.18915 -0.12029 0.01478 -0.10045 ...
 $ FrequencyBodyGyroscopeMeanFreq()-Y               : num  -0.0915 0.0631 -0.0447 -0.0658 0.0826 ...
 $ FrequencyBodyGyroscopeMeanFreq()-Z               : num  0.010458 -0.029784 0.100608 0.000773 -0.075676 ...
 $ FrequencyBodyAccelerometerMagnitudeMean()        : num  -0.8618 -0.9478 -0.9854 -0.1286 0.0966 ...
 $ FrequencyBodyAccelerometerMagnitudeSTD()         : num  -0.798 -0.928 -0.982 -0.398 -0.187 ...
 $ FrequencyBodyAccelerometerMagnitudeMeanFreq()    : num  0.0864 0.2367 0.2846 0.1906 0.1192 ...
 $ FrequencyBodyAccelerometerJerkMagnitudeMean()    : num  -0.9333 -0.9853 -0.9925 -0.0571 0.0262 ...
 $ FrequencyBodyAccelerometerJerkMagnitudeSTD()     : num  -0.922 -0.982 -0.993 -0.103 -0.104 ...
 $ FrequencyBodyAccelerometerJerkMagnitudeMeanFreq(): num  0.2664 0.3519 0.4222 0.0938 0.0765 ...
 $ FrequencyBodyGyroscopeMagnitudeMean()            : num  -0.862 -0.958 -0.985 -0.199 -0.186 ...
 $ FrequencyBodyGyroscopeMagnitudeSTD()             : num  -0.824 -0.932 -0.978 -0.321 -0.398 ...
 $ FrequencyBodyGyroscopeMagnitudeMeanFreq()        : num  -0.139775 -0.000262 -0.028606 0.268844 0.349614 ...
 $ FrequencyBodyGyroscopeJerkMagnitudeMean()        : num  -0.942 -0.99 -0.995 -0.319 -0.282 ...
 $ FrequencyBodyGyroscopeJerkMagnitudeSTD()         : num  -0.933 -0.987 -0.995 -0.382 -0.392 ...
 $ FrequencyBodyGyroscopeJerkMagnitudeMeanFreq()    : num  0.176 0.185 0.334 0.191 0.19 ...
 $ Angle(TimeBodyAccelerometerMean,Gravity)         : num  0.021366 0.027442 -0.000222 0.060454 -0.002695 ...
 $ Angle(TimeBodyAccelerometerJerkMean),GravityMean): num  0.00306 0.02971 0.02196 -0.00793 0.08993 ...
 $ Angle(TimeBodyGyroscopeMean,GravityMean)         : num  -0.00167 0.0677 -0.03379 0.01306 0.06334 ...
 $ Angle(TimeBodyGyroscopeJerkMean,GravityMean)     : num  0.0844 -0.0649 -0.0279 -0.0187 -0.04 ...
 $ Angle(X,GravityMean)                             : num  0.427 -0.591 -0.743 -0.729 -0.744 ...
 $ Angle(Y,GravityMean)                             : num  -0.5203 -0.0605 0.2702 0.277 0.2672 ...
 $ Angle(Z,GravityMean)                             : num  -0.3524 -0.218 0.0123 0.0689 0.065 ...
> library(knitr)
> knit2html("codebook.Rmd");
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'codebook.Rmd': No such file or directory
> knit2html("codebook.Rmd")
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'codebook.Rmd': No such file or directory
> 
> knit2html("Tidy.txt")
> codebook <- knit2html("Tidy.txt")
> codebook
[1] "Tidy-out.html"
> str(tidyData)
'data.frame':	180 obs. of  88 variables:
 $ Subject                                          : Factor w/ 30 levels "1","2","3","4",..: 1 1 1 1 1 1 2 2 2 2 ...
 $ Activity                                         : Factor w/ 6 levels "LAYING","SITTING",..: 1 2 3 4 5 6 1 2 3 4 ...
 $ TimeBodyAccelerometerMean()-X                    : num  0.222 0.261 0.279 0.277 0.289 ...
 $ TimeBodyAccelerometerMean()-Y                    : num  -0.04051 -0.00131 -0.01614 -0.01738 -0.00992 ...
 $ TimeBodyAccelerometerMean()-Z                    : num  -0.113 -0.105 -0.111 -0.111 -0.108 ...
 $ TimeBodyAccelerometerSTD()-X                     : num  -0.928 -0.977 -0.996 -0.284 0.03 ...
 $ TimeBodyAccelerometerSTD()-Y                     : num  -0.8368 -0.9226 -0.9732 0.1145 -0.0319 ...
 $ TimeBodyAccelerometerSTD()-Z                     : num  -0.826 -0.94 -0.98 -0.26 -0.23 ...
 $ TimeGravityAccelerometerMean()-X                 : num  -0.249 0.832 0.943 0.935 0.932 ...
 $ TimeGravityAccelerometerMean()-Y                 : num  0.706 0.204 -0.273 -0.282 -0.267 ...
 $ TimeGravityAccelerometerMean()-Z                 : num  0.4458 0.332 0.0135 -0.0681 -0.0621 ...
 $ TimeGravityAccelerometerSTD()-X                  : num  -0.897 -0.968 -0.994 -0.977 -0.951 ...
 $ TimeGravityAccelerometerSTD()-Y                  : num  -0.908 -0.936 -0.981 -0.971 -0.937 ...
 $ TimeGravityAccelerometerSTD()-Z                  : num  -0.852 -0.949 -0.976 -0.948 -0.896 ...
 $ TimeBodyAccelerometerJerkMean()-X                : num  0.0811 0.0775 0.0754 0.074 0.0542 ...
 $ TimeBodyAccelerometerJerkMean()-Y                : num  0.003838 -0.000619 0.007976 0.028272 0.02965 ...
 $ TimeBodyAccelerometerJerkMean()-Z                : num  0.01083 -0.00337 -0.00369 -0.00417 -0.01097 ...
 $ TimeBodyAccelerometerJerkSTD()-X                 : num  -0.9585 -0.9864 -0.9946 -0.1136 -0.0123 ...
 $ TimeBodyAccelerometerJerkSTD()-Y                 : num  -0.924 -0.981 -0.986 0.067 -0.102 ...
 $ TimeBodyAccelerometerJerkSTD()-Z                 : num  -0.955 -0.988 -0.992 -0.503 -0.346 ...
 $ TimeBodyGyroscopeMean()-X                        : num  -0.0166 -0.0454 -0.024 -0.0418 -0.0351 ...
 $ TimeBodyGyroscopeMean()-Y                        : num  -0.0645 -0.0919 -0.0594 -0.0695 -0.0909 ...
 $ TimeBodyGyroscopeMean()-Z                        : num  0.1487 0.0629 0.0748 0.0849 0.0901 ...
 $ TimeBodyGyroscopeSTD()-X                         : num  -0.874 -0.977 -0.987 -0.474 -0.458 ...
 $ TimeBodyGyroscopeSTD()-Y                         : num  -0.9511 -0.9665 -0.9877 -0.0546 -0.1263 ...
 $ TimeBodyGyroscopeSTD()-Z                         : num  -0.908 -0.941 -0.981 -0.344 -0.125 ...
 $ TimeBodyGyroscopeJerkMean()-X                    : num  -0.1073 -0.0937 -0.0996 -0.09 -0.074 ...
 $ TimeBodyGyroscopeJerkMean()-Y                    : num  -0.0415 -0.0402 -0.0441 -0.0398 -0.044 ...
 $ TimeBodyGyroscopeJerkMean()-Z                    : num  -0.0741 -0.0467 -0.049 -0.0461 -0.027 ...
 $ TimeBodyGyroscopeJerkSTD()-X                     : num  -0.919 -0.992 -0.993 -0.207 -0.487 ...
 $ TimeBodyGyroscopeJerkSTD()-Y                     : num  -0.968 -0.99 -0.995 -0.304 -0.239 ...
 $ TimeBodyGyroscopeJerkSTD()-Z                     : num  -0.958 -0.988 -0.992 -0.404 -0.269 ...
 $ TimeBodyAccelerometerMagnitudeMean()             : num  -0.8419 -0.9485 -0.9843 -0.137 0.0272 ...
 $ TimeBodyAccelerometerMagnitudeSTD()              : num  -0.7951 -0.9271 -0.9819 -0.2197 0.0199 ...
 $ TimeGravityAccelerometerMagnitudeMean()          : num  -0.8419 -0.9485 -0.9843 -0.137 0.0272 ...
 $ TimeGravityAccelerometerMagnitudeSTD()           : num  -0.7951 -0.9271 -0.9819 -0.2197 0.0199 ...
 $ TimeBodyAccelerometerJerkMagnitudeMean()         : num  -0.9544 -0.9874 -0.9924 -0.1414 -0.0894 ...
 $ TimeBodyAccelerometerJerkMagnitudeSTD()          : num  -0.9282 -0.9841 -0.9931 -0.0745 -0.0258 ...
 $ TimeBodyGyroscopeMagnitudeMean()                 : num  -0.8748 -0.9309 -0.9765 -0.161 -0.0757 ...
 $ TimeBodyGyroscopeMagnitudeSTD()                  : num  -0.819 -0.935 -0.979 -0.187 -0.226 ...
 $ TimeBodyGyroscopeJerkMagnitudeMean()             : num  -0.963 -0.992 -0.995 -0.299 -0.295 ...
 $ TimeBodyGyroscopeJerkMagnitudeSTD()              : num  -0.936 -0.988 -0.995 -0.325 -0.307 ...
 $ FrequencyBodyAccelerometerMean()-X               : num  -0.9391 -0.9796 -0.9952 -0.2028 0.0382 ...
 $ FrequencyBodyAccelerometerMean()-Y               : num  -0.86707 -0.94408 -0.97707 0.08971 0.00155 ...
 $ FrequencyBodyAccelerometerMean()-Z               : num  -0.883 -0.959 -0.985 -0.332 -0.226 ...
 $ FrequencyBodyAccelerometerSTD()-X                : num  -0.9244 -0.9764 -0.996 -0.3191 0.0243 ...
 $ FrequencyBodyAccelerometerSTD()-Y                : num  -0.834 -0.917 -0.972 0.056 -0.113 ...
 $ FrequencyBodyAccelerometerSTD()-Z                : num  -0.813 -0.934 -0.978 -0.28 -0.298 ...
 $ FrequencyBodyAccelerometerMeanFreq()-X           : num  -0.1588 -0.0495 0.0865 -0.2075 -0.3074 ...
 $ FrequencyBodyAccelerometerMeanFreq()-Y           : num  0.0975 0.0759 0.1175 0.1131 0.0632 ...
 $ FrequencyBodyAccelerometerMeanFreq()-Z           : num  0.0894 0.2388 0.2449 0.0497 0.2943 ...
 $ FrequencyBodyAccelerometerJerkMean()-X           : num  -0.9571 -0.9866 -0.9946 -0.1705 -0.0277 ...
 $ FrequencyBodyAccelerometerJerkMean()-Y           : num  -0.9225 -0.9816 -0.9854 -0.0352 -0.1287 ...
 $ FrequencyBodyAccelerometerJerkMean()-Z           : num  -0.948 -0.986 -0.991 -0.469 -0.288 ...
 $ FrequencyBodyAccelerometerJerkSTD()-X            : num  -0.9642 -0.9875 -0.9951 -0.1336 -0.0863 ...
 $ FrequencyBodyAccelerometerJerkSTD()-Y            : num  -0.932 -0.983 -0.987 0.107 -0.135 ...
 $ FrequencyBodyAccelerometerJerkSTD()-Z            : num  -0.961 -0.988 -0.992 -0.535 -0.402 ...
 $ FrequencyBodyAccelerometerJerkMeanFreq()-X       : num  0.132 0.257 0.314 -0.209 -0.253 ...
 $ FrequencyBodyAccelerometerJerkMeanFreq()-Y       : num  0.0245 0.0475 0.0392 -0.3862 -0.3376 ...
 $ FrequencyBodyAccelerometerJerkMeanFreq()-Z       : num  0.02439 0.09239 0.13858 -0.18553 0.00937 ...
 $ FrequencyBodyGyroscopeMean()-X                   : num  -0.85 -0.976 -0.986 -0.339 -0.352 ...
 $ FrequencyBodyGyroscopeMean()-Y                   : num  -0.9522 -0.9758 -0.989 -0.1031 -0.0557 ...
 $ FrequencyBodyGyroscopeMean()-Z                   : num  -0.9093 -0.9513 -0.9808 -0.2559 -0.0319 ...
 $ FrequencyBodyGyroscopeSTD()-X                    : num  -0.882 -0.978 -0.987 -0.517 -0.495 ...
 $ FrequencyBodyGyroscopeSTD()-Y                    : num  -0.9512 -0.9623 -0.9871 -0.0335 -0.1814 ...
 $ FrequencyBodyGyroscopeSTD()-Z                    : num  -0.917 -0.944 -0.982 -0.437 -0.238 ...
 $ FrequencyBodyGyroscopeMeanFreq()-X               : num  -0.00355 0.18915 -0.12029 0.01478 -0.10045 ...
 $ FrequencyBodyGyroscopeMeanFreq()-Y               : num  -0.0915 0.0631 -0.0447 -0.0658 0.0826 ...
 $ FrequencyBodyGyroscopeMeanFreq()-Z               : num  0.010458 -0.029784 0.100608 0.000773 -0.075676 ...
 $ FrequencyBodyAccelerometerMagnitudeMean()        : num  -0.8618 -0.9478 -0.9854 -0.1286 0.0966 ...
 $ FrequencyBodyAccelerometerMagnitudeSTD()         : num  -0.798 -0.928 -0.982 -0.398 -0.187 ...
 $ FrequencyBodyAccelerometerMagnitudeMeanFreq()    : num  0.0864 0.2367 0.2846 0.1906 0.1192 ...
 $ FrequencyBodyAccelerometerJerkMagnitudeMean()    : num  -0.9333 -0.9853 -0.9925 -0.0571 0.0262 ...
 $ FrequencyBodyAccelerometerJerkMagnitudeSTD()     : num  -0.922 -0.982 -0.993 -0.103 -0.104 ...
 $ FrequencyBodyAccelerometerJerkMagnitudeMeanFreq(): num  0.2664 0.3519 0.4222 0.0938 0.0765 ...
 $ FrequencyBodyGyroscopeMagnitudeMean()            : num  -0.862 -0.958 -0.985 -0.199 -0.186 ...
 $ FrequencyBodyGyroscopeMagnitudeSTD()             : num  -0.824 -0.932 -0.978 -0.321 -0.398 ...
 $ FrequencyBodyGyroscopeMagnitudeMeanFreq()        : num  -0.139775 -0.000262 -0.028606 0.268844 0.349614 ...
 $ FrequencyBodyGyroscopeJerkMagnitudeMean()        : num  -0.942 -0.99 -0.995 -0.319 -0.282 ...
 $ FrequencyBodyGyroscopeJerkMagnitudeSTD()         : num  -0.933 -0.987 -0.995 -0.382 -0.392 ...
 $ FrequencyBodyGyroscopeJerkMagnitudeMeanFreq()    : num  0.176 0.185 0.334 0.191 0.19 ...
 $ Angle(TimeBodyAccelerometerMean,Gravity)         : num  0.021366 0.027442 -0.000222 0.060454 -0.002695 ...
 $ Angle(TimeBodyAccelerometerJerkMean),GravityMean): num  0.00306 0.02971 0.02196 -0.00793 0.08993 ...
 $ Angle(TimeBodyGyroscopeMean,GravityMean)         : num  -0.00167 0.0677 -0.03379 0.01306 0.06334 ...
 $ Angle(TimeBodyGyroscopeJerkMean,GravityMean)     : num  0.0844 -0.0649 -0.0279 -0.0187 -0.04 ...
 $ Angle(X,GravityMean)                             : num  0.427 -0.591 -0.743 -0.729 -0.744 ...
 $ Angle(Y,GravityMean)                             : num  -0.5203 -0.0605 0.2702 0.277 0.2672 ...
 $ Angle(Z,GravityMean)                             : num  -0.3524 -0.218 0.0123 0.0689 0.065 ...